package com.artedprvt.core.localization.types;

import com.artedprvt.iv.anno.InterfaceView;

public class CIS {

    public static final String
            cis0 = "模组命令集合",
            cis1 = "命令",
            cis2 = "未知命令",
            cis3 = "运行应用程序",
            cis4 = "应用程序路径",
            cis5 = "应用程序不存在",
            cis6 = "项目管理工具 {0}[{1}]",
            cis7 = "未打开项目",
            cis8 = "打开项目",
            cis9 = "初始化项目",
            cis10 = "加载项目",
            cis11 = "关闭项目",
            cis12 = "无效目录",
            cis13 = "选择内置初始化器或指定URL",
            cis14 = "无效URL",
            cis15 = "从此位置下载初始化器",
            cis16 = "查看运行中的应用进程",
            cis17 = "pid",
            cis18 = "停止运行中的应用进程",
            cis19 = "项目构建工具 {0}[{1}]",
            cis20 = "未加载项目",
            cis21 = "",
            cis22 = "",
            cis23 = "",
            cis24 = "",
            cis25 = "",
            cis26 = "",
            cis27 = "",
            cis28 = "",
            cis29 = "",
            cis30 = "",
            cis31 = "",
            cis32 = "",
            cis33 = "",
            cis34 = "",
            cis35 = "",
            cis36 = "",
            cis37 = "",
            cis38 = "",
            cis39 = "",
            cis40 = "",
            cis41 = "",
            cis42 = "",
            cis43 = "",
            cis44 = "",
            cis45 = "",
            cis46 = "",
            cis47 = "",
            cis48 = "",
            cis49 = "",
            cis50 = "",
            cis51 = "",
            cis52 = "",
            cis53 = "",
            cis54 = "",
            cis55 = "",
            cis56 = "",
            cis57 = "",
            cis58 = "",
            cis59 = "",
            cis60 = "",
            cis61 = "",
            cis62 = "",
            cis63 = "";
}
