cis0="未知命令"
cis1="未知aar"
cis2="未知模块"
cis3="意外的参数"
cis4="命令"
cis5="aar路径"
cis6="模块名"
cis7="进程ID|名称|ID"
cis8="属性|load"
cis9="无效属性"
cis10="输入"
cis11="重新加载"
cis12=""
cis13=""
cis14=""
cis15=""
cis16=""
cis17=""
cis18=""
cis19=""
cis20=""
cis21=""
cis22=""
cis23=""
cis24=""
cis25=""
cis26=""
cis27=""
cis28=""
cis29=""
cis30=""
cis31=""
cis32=""
cis33=""
cis34=""
cis35=""
cis36=""
cis37=""
cis38=""
cis39=""
cis40=""
cis41=""
cis42=""
cis43=""
cis44=""
cis45=""
cis46=""
cis47=""
cis48=""
cis49=""
cis50=""
cis51=""
cis52=""
cis53=""
cis54=""
cis55=""
cis56=""
cis57=""
cis58=""
cis59=""
cis60=""
cis61=""
cis62=""
cis63=""