cms0="不能有参数"
cms1="参数不能为空"
cms2="包名格式异常"
cms3="脚本进程创建失败: {0}"
cms4="找不到artedprvt目录"
cms5="解析apkg.info时失败"
cms6="构建成功"
cms7="构建失败"
cms8="src目录已有文件"
cms9="提取成功"
cms10="提取失败"
cms11="没有进程"
cms12="切换chat状态到: {0}"
cms13="切换debug状态到: {0}"
cms14="找不到命令: {0}"
cms15="找不到和 {0} 相关的进程"
cms16="只能有最多一个参数"
cms17="模块名格式异常"
cms18="没有进程"
cms19="/artedprvt目录已经存在"
cms20="/artedprvt目录创建失败"
cms21="文件解压失败"
cms22="文件写入异常"
cms23="工作空间构建成功"
cms24=""
cms25=""
cms26=""
cms27=""
cms28=""
cms29=""
cms30=""
cms31=""
cms32=""
cms33=""
cms34=""
cms35=""
cms36=""
cms37=""
cms38=""
cms39=""
cms40=""
cms41=""
cms42=""
cms43=""
cms44=""
cms45=""
cms46=""
cms47=""
cms48=""
cms49=""
cms50=""
cms51=""
cms52=""
cms53=""
cms54=""
cms55=""
cms56=""
cms57=""
cms58=""
cms59=""