tms0="任务管理器"
tms1="名称"
tms2="内存"
tms3="CPU"
tms4="PID"
tms5="脚本进程"
tms6="其他进程"
tms7="进程控制器"
tms8="文件"
tms9="运行Apkg"
tms10="运行脚本"
tms11="关闭"
tms12="帮助"
tms13="关于"
tms14="运行Apkg"
tms15="<html>根据你键入的名称和参数创建apkg的脚本进程。</html>"
tms16="运行脚本"
tms17="<html>根据你键入的名称和参数创建脚本进程。</html>"
tms18="关于任务管理器"
tms19="<html>任务管理器展示脚本进程的几乎所有有用的信息。</html>"
tms20="停止"
tms21="重启"
tms22="属性"
tms23="图形环境不支持"
tms24=""
tms25=""
tms26=""
tms27=""
tms28=""
tms29=""
tms30=""
tms31=""
tms32=""
tms33=""
tms34=""
tms35=""
tms36=""
tms37=""
tms38=""
tms39=""
tms40=""
tms41=""
tms42=""
tms43=""
tms44=""
tms45=""
tms46=""
tms47=""
tms48=""
tms49=""
tms50=""
tms51=""
tms52=""
tms53=""
tms54=""
tms55=""
tms56=""
tms57=""
tms58=""
tms59=""